#! /bin/bash
# Clears the log files

if [ "$1" != "" ]; then cd "$1"; fi
LOGDIR=`jq '.["LOG_CONFIG"]["LOGDIR"]' config.json -r`

# write date to all the files
echo "
----- `date` -----
" | tee `find "$LOGDIR" -type f`
