#! /bin/bash
# starts the bot

if [ "$1" != "" ]; then cd "$1"; fi

LOG_CONFIG=`jq '.["LOG_CONFIG"]' config.json -cM`
for var in LOGDIR LOG ERR
do
	val=`echo $LOG_CONFIG | jq '.["'"$var"'"]' -r`
	if [ "$var" != "LOGDIR" ]; then declare "$var=$LOGDIR/$val"
	else declare "$var=$val"; fi
done

pwd && sleep 5 # print current directory and give user chance to abort if in wrong dir

mkdir -p "$LOGDIR" # make log dir
# add date to both logs
echo "
----- `date` -----
" | tee -a "$LOG" "$ERR"

# stdout appends to LOG, stderr appends to ERR
python3 BOI1.py >> "$LOG" 2>> "$ERR" &
